version: "3"

# Jetson Nano  JetPack 4.6  (ARM64)
# Usage: docker compose -f docker-compose.jetson.yml up --build
# docker-compose -f docker-compose.yolov8-trt-jetson-nano.yml build
# docker-compose -f docker-compose.yolov8-trt-jetson-nano.yml push
#
# Requires nvidia-container-runtime on the Nano:
#   sudo apt install nvidia-container-runtime
#   sudo systemctl restart docker

services:
  data_logger:
    build:
      context: .
      dockerfile: Dockerfile.jetson
    image: meraquetech/race_nav:data-logger-jetson
    container_name: data_logger_jetson
    restart: always
    # ports: not needed with network_mode: host — port 5000 is directly on the host
    volumes:
      - ./logs:/app/logs
      - /bin/systemctl:/bin/systemctl
      - /run/systemd/system:/run/systemd/system
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw  # Allow the container to control Docker on the host
      - /var/run/dbus:/var/run/dbus
      - /dev/mem:/dev/mem
    network_mode: host   # needed for nmcli to reach NetworkManager and for hostname -I to show host IPs
    privileged: true
    # devices:
    #   - /dev/video0:/dev/video0
    #   - /dev/video1:/dev/video1
    #   - /dev/video2:/dev/video2
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=video,compute,utility


