# x86_64  Ubuntu 22.04
# Usage: docker compose -f docker-compose.x86.yml up --build

services:
  data_logger:
    build:
      context: .
      dockerfile: Dockerfile.x86
    image: meraquetech/race_nav:data-logger-x86
    container_name: data_logger_x86
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
      - /dev/video0:/dev/video0
    group_add:
      - video
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
