version: "3.3"

services:
  bwt901ble_imu:
    image: meraquetech/race_nav:bwt901ble_imu.humble.jetson.v2
    container_name: bwt901ble_imu
    build:
      context: ./vision/sf
      dockerfile: Dockerfile.bwt901ble_imu
    command: >
      ros2 launch bwt901ble_imu imu_gps_raw.launch.py
    tty: true
    hostname: bwt901ble_imu
    user: "0:0"
    privileged: true
    group_add:
      - "20"
    network_mode: host
    ipc: host
    restart: always
    stop_grace_period: 5s
    tmpfs:
      - /tmp
    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:rw
      - ./cyclone_dds_profile.xml:/dds_ws/cyclone_dds_profile.xml:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - HOME=/tmp
      - ROS_HOME=/tmp/ros
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///dds_ws/cyclone_dds_profile.xml

  rosbag_recorder:
    image: meraquetech/race_nav:bwt901ble_imu.humble.jetson.v2
    container_name: rosbag_recorder
    depends_on:
      - bwt901ble_imu
    network_mode: host
    ipc: host
    restart: always
    user: "0:0"
    tty: true
    volumes:
      - ./bags:/bags
      - ./cyclone_dds_profile.xml:/dds_ws/cyclone_dds_profile.xml:ro
    environment:
      - HOME=/tmp
      - ROS_HOME=/tmp/ros
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///dds_ws/cyclone_dds_profile.xml
    command: >
      bash -c "
      sleep 10 &&
      source /opt/ros/humble/setup.bash &&
      ros2 bag record
      -o /bags/imu_gps_$(date +%Y%m%d_%H%M%S)
      /gnss/pvt
      /imu/data
      "