FROM meraquetech/race_nav:humble.sensors.dep_jetson AS base

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive \
    ROS_DISTRO=humble \
    AGV_WS=/opt/agv_ws \
    DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket



WORKDIR ${AGV_WS}



COPY ./bwt901ble_imu src/bwt901ble_imu
COPY ./prime_msgs src/prime_msgs
COPY ./base_receiver src/base_receiver
COPY ./rtk_localization src/rtk_localization


RUN source /opt/ros/${ROS_DISTRO}/setup.bash \
    && colcon build \
        --merge-install --symlink-install

# Copy custom entrypoint
COPY ./amr_entrypoint.bash /amr_entrypoint.bash
RUN chmod +x /amr_entrypoint.bash

# Entrypoint
ENTRYPOINT ["/amr_entrypoint.bash"]
# CMD ["ros2", "launch", "rtk_localization", "imu_gps_raw.launch.py"]


# docker buildx build --platform linux/amd64,linux/arm64 \
#     -f Dockerfile.sf.humble \
#     -t meraquetech/race_nav:sf.humble.v3 \
#     --push \
#     .