FROM ros:humble-ros-base-jammy

# Select bash as default shell
SHELL ["/bin/bash", "-c"]

ENV AGV_WS="/agv_ws"
WORKDIR ${AGV_WS}


RUN source /opt/ros/${ROS_DISTRO}/setup.sh \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        # general tools
        ros-dev-tools \
        iputils-ping \
        net-tools \
        iproute2 \
        unzip \
        wget \
        nano \
        build-essential \
        cmake \
        python3-pip \
        python3-dev \
        python3-pymap3d \
        python3-serial \
        libomp-dev \
        bluez \
        dbus \
        nlohmann-json3-dev \
        \
        # ROS core
        ros-${ROS_DISTRO}-ament-cmake \
        ros-${ROS_DISTRO}-rclcpp \
        ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
        ros-${ROS_DISTRO}-ros-testing \
        \
        # ROS msgs & TF
        ros-${ROS_DISTRO}-std-msgs \
        ros-${ROS_DISTRO}-geometry-msgs \
        ros-${ROS_DISTRO}-nav-msgs \
        ros-${ROS_DISTRO}-sensor-msgs \
        ros-${ROS_DISTRO}-visualization-msgs \
        ros-${ROS_DISTRO}-std-srvs \
        ros-${ROS_DISTRO}-tf2 \
        ros-${ROS_DISTRO}-tf2-ros \
        ros-${ROS_DISTRO}-tf2-geometry-msgs \
        \
        # PCL (system)
        libpcl-dev \
        ros-${ROS_DISTRO}-pcl-conversions \
        \
        # GeographicLib (system)
        libgeographic-dev \
        geographiclib-tools \
        ros-${ROS_DISTRO}-diagnostic-updater \
        \
        # sensor drivers / localization
        ros-${ROS_DISTRO}-microstrain-inertial-driver \
        ros-${ROS_DISTRO}-microstrain-inertial-rqt \
        ros-${ROS_DISTRO}-imu-tools \
        ros-${ROS_DISTRO}-robot-localization \
    && python3 -m pip install --no-cache-dir 'bleak>=0.20' \
    && rosdep init || echo "rosdep already initialized" \
    && rosdep update \
    && rm -rf /var/lib/apt/lists/*

# RUN git clone https://github.com/Livox-SDK/Livox-SDK2.git \
#         && cd ./Livox-SDK2/ \
#         && mkdir build \
#         && cd build \
#         && cmake .. && make -j \
#         && sudo make install

# sudo systemctl restart bluetooth
# docker build -f Dockerfile.sensors.dep -t meraquetech/race_nav:humble.sensors.dep_jetson .
# docker push meraquetech/race_nav:humble.sensors.dep_jetson