FROM meraquetech/race_nav:humble.imu.dep_jetson AS base

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive \
    ROS_DISTRO=humble \
    AGV_WS=/opt/agv_ws \
    DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket

RUN apt-get update && apt-get install -y --no-install-recommends \
        bluez \
        dbus \
        python3-pip \
        python3-pymap3d \
        python3-serial \
        nlohmann-json3-dev \
        ros-${ROS_DISTRO}-robot-localization \
    && python3 -m pip install --no-cache-dir 'bleak>=0.20' \
    && rm -rf /var/lib/apt/lists/*

WORKDIR ${AGV_WS}
COPY ./bwt901ble_imu src/bwt901ble_imu
COPY ./ros2-gnss-imu-fusion src/ros2-gnss-imu-fusion

RUN source /opt/ros/${ROS_DISTRO}/setup.bash \
    && colcon build \
        --merge-install --symlink-install

# Copy custom entrypoint
COPY ./amr_entrypoint.bash /amr_entrypoint.bash
RUN chmod +x /amr_entrypoint.bash

# Entrypoint
ENTRYPOINT ["/amr_entrypoint.bash"]
CMD ["ros2", "launch", "bwt901ble_imu", "imu.launch.py"]

# docker build -f Dockerfile.bwt901ble_imu -t meraquetech/race_nav:bwt901ble_imu.humble.jetson .
# docker push meraquetech/race_nav:bwt901ble_imu.humble.jetson