FROM ros:humble-ros-base-jammy

# Select bash as default shell
SHELL ["/bin/bash", "-c"]

ENV AGV_WS="/agv_ws"
WORKDIR ${AGV_WS}


RUN source /opt/ros/${ROS_DISTRO}/setup.sh \
    && apt-get update \
    && apt-get install -y --no-install-recommends ros-dev-tools \
        libpcl-dev \
        iputils-ping \
        net-tools \
        iproute2 \
        python3-pip \
        unzip \
        wget \
        nano \
        ros-dev-tools \
        build-essential \
        libomp-dev \
        ros-${ROS_DISTRO}-microstrain-inertial-driver\
        ros-${ROS_DISTRO}-microstrain-inertial-rqt \
        ros-${ROS_DISTRO}-ros-testing \
        ros-${ROS_DISTRO}-imu-tools \
        ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
        ros-${ROS_DISTRO}-diagnostic-updater && \
        rosdep init || echo "rosdep already initialized" && \
        rosdep update && \
        rm -rf /var/lib/apt/lists/*

# RUN git clone https://github.com/Livox-SDK/Livox-SDK2.git \
#         && cd ./Livox-SDK2/ \
#         && mkdir build \
#         && cd build \
#         && cmake .. && make -j \
#         && sudo make install

# docker build -f Dockerfile.imu.dep -t meraquetech/race_nav:humble.imu.dep_jetson .
# docker push meraquetech/race_nav:humble.imu.dep_jetson