name: base-receiver

services:
  base_receiver:
    image: meraquetech/race_nav:base_receiver.v6
    build: .
    container_name: base_receiver
    hostname: mardi
    user: "0:0"
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    network_mode: host
    ipc: host
    privileged: true
    group_add:
      - "20"
    command:
      - ros2
      - launch
      - base_receiver
      - receiver.launch.py

# Usage:
#   docker compose -f docker-compose.base_receiver.yaml build
#   docker compose -f docker-compose.base_receiver.yaml up -d
#   docker compose -f docker-compose.base_receiver.yaml exec base_receiver bash
#   docker compose -f docker-compose.base_receiver.yaml logs -f
#   docker compose -f docker-compose.base_receiver.yaml restart
#   docker compose -f docker-compose.base_receiver.yaml down
#
# Rebuild and recreate after Dockerfile changes:
#   docker compose -f docker-compose.base_receiver.yaml up -d --build --force-recreate

# on jetson: docker exec -it base_receiver bash
# ros2 bag record -a
# docker cp base_receiver:/ros2_ws/rosbag2_2026_08_03-02_29_59 ./rosbags
# on local: scp -r mardi@100.85.58.71:/home/mardi/Mardi_tech/rosbags /home/aloy/Mardi_tech/
