services:
  yolov8-trt-serialize-x86-jazzy:
    image: meraquetech/race_nav:yolov8-trt-bed-detect-x86.ros2.jazzy.v3
    container_name: yolov8-trt-serialize-x86-jazzy
    # build:
    #   context: .
    #   dockerfile: Dockerfile.yolov8_trt_x86.ros2.jazzy
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./yolov8/weights:/weights
    runtime: nvidia
    restart: "no"
    command: >
      bash -c "source /opt/ros/jazzy/setup.bash &&
               source /ros2_ws/install/setup.bash &&
               ros2 run yolov8_trt_bed_detect_orin yolov8_trt_bed_detect_orin -s /weights/yolov8n.wts /weights/yolov8n_x86_ros2_jazzy.engine n 512 512"

  yolov8-trt-bed-detect-x86-jazzy:
    image: meraquetech/race_nav:yolov8-trt-bed-detect-x86.ros2.jazzy.v3
    container_name: yolov8-trt-bed-detect-x86-jazzy
    build:
      context: .
      dockerfile: Dockerfile.yolov8_trt_x86.ros2.jazzy
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - GNSS_FIX_TOPIC=/receiver/fix
      - GNSS_STALE_TIMEOUT=3.0
      - FORWARD_TOPIC=/gnss/is_forward
      - BACKWARD_TOPIC=/gnss/is_backward
      - DIRECTION_STALE_TIMEOUT=3.0
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      # - /dev/video4:/dev/video4
    volumes:
      - ./yolov8/weights:/weights
      - ./yolov8_trt_bed_detect_orin/config:/ros2_ws/install/yolov8_trt_bed_detect_orin/share/yolov8_trt_bed_detect_orin/config
      - ./yolov8_trt_bed_detect_orin/launch:/ros2_ws/install/yolov8_trt_bed_detect_orin/share/yolov8_trt_bed_detect_orin/launch
      - ./saved_frames:/saved_frames
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    # privileged: false
    runtime: nvidia
    # depends_on:
    #   yolov8-trt-serialize-x86-jazzy:
    #     condition: service_completed_successfully
    command: >
      bash -c "source /opt/ros/jazzy/setup.bash &&
               source /ros2_ws/install/setup.bash &&
               ros2 launch yolov8_trt_bed_detect_orin bed_detect.launch.py"

# Usage:
#   mkdir -p saved_frames
#   docker compose -f docker-compose.yolov8-trt-bed-detect-x86.ros2.jazzy.yml build
#   docker compose -f docker-compose.yolov8-trt-bed-detect-x86.ros2.jazzy.yml run --rm yolov8-trt-serialize-x86-jazzy
#   docker compose -f docker-compose.yolov8-trt-bed-detect-x86.ros2.jazzy.yml up yolov8-trt-bed-detect-x86-jazzy
#   docker compose -f docker-compose.yolov8-trt-bed-detect-x86.ros2.jazzy.yml up -d yolov8-trt-bed-detect-x86-jazzy
#   docker compose -f docker-compose.yolov8-trt-bed-detect-x86.ros2.jazzy.yml exec yolov8-trt-bed-detect-x86-jazzy bash
#   docker compose -f docker-compose.yolov8-trt-bed-detect-x86.ros2.jazzy.yml logs -f
#   docker compose -f docker-compose.yolov8-trt-bed-detect-x86.ros2.jazzy.yml down
