services:
  yolov8-trt-serialize-x86-humble:
    image: meraquetech/race_nav:yolov8-trt-bed-detect-x86.ros2.humble
    container_name: yolov8-trt-serialize-x86-humble
    # build:
    #   context: .
    #   dockerfile: Dockerfile.yolov8_trt_x86.ros2.humble
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./yolov8/weights:/weights
    runtime: nvidia
    restart: "no"
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
               source /ros2_ws/install/setup.bash &&
               ros2 run yolov8_trt_bed_detect_orin yolov8_trt_bed_detect_orin -s /weights/yolov8n.wts /weights/yolov8n_x86_ros2_humble.engine n 512 512"

  yolov8-trt-bed-detect-x86-humble:
    image: meraquetech/race_nav:yolov8-trt-bed-detect-x86.ros2.humble
    container_name: yolov8-trt-bed-detect-x86-humble
    build:
      context: .
      dockerfile: Dockerfile.yolov8_trt_x86.ros2.humble
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
    volumes:
      - ./yolov8/weights:/weights
      - ./yolov8_trt_bed_detect_orin/config:/ros2_ws/install/yolov8_trt_bed_detect_orin/share/yolov8_trt_bed_detect_orin/config
      - ./yolov8_trt_bed_detect_orin/launch:/ros2_ws/install/yolov8_trt_bed_detect_orin/share/yolov8_trt_bed_detect_orin/launch
      - ./saved_frames:/saved_frames
    network_mode: host
    pid: host
    privileged: true
    runtime: nvidia
    # depends_on:
    #   yolov8-trt-serialize-x86-humble:
    #     condition: service_completed_successfully
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
               source /ros2_ws/install/setup.bash &&
               ros2 launch yolov8_trt_bed_detect_orin bed_detect.launch.py"

# Usage:
#   mkdir -p saved_frames
#   docker compose -f docker-compose.yolov8-trt-bed-detect-x86.ros2.humble.yml build
#   docker compose -f docker-compose.yolov8-trt-bed-detect-x86.ros2.humble.yml run --rm yolov8-trt-serialize-x86-humble
#   docker compose -f docker-compose.yolov8-trt-bed-detect-x86.ros2.humble.yml up -d
#   docker compose -f docker-compose.yolov8-trt-bed-detect-x86.ros2.humble.yml exec yolov8-trt-bed-detect-x86-humble bash
#   docker compose -f docker-compose.yolov8-trt-bed-detect-x86.ros2.humble.yml logs -f
#   docker compose -f docker-compose.yolov8-trt-bed-detect-x86.ros2.humble.yml down
