
# FROM nvcr.io/nvidia/l4t-jetpack:r36.4.0
FROM nvcr.io/nvidia/l4t-jetpack:r36.4.0

ENV DEBIAN_FRONTEND=noninteractive
ENV OPENBLAS_CORETYPE=ARMV8
# ENV CUDA_HOME=/usr/local/cuda
# ENV CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda
# Select bash as default shell
SHELL ["/bin/bash", "-c"]


