yolov8_trt:
  ros__parameters:
    engine_name: /weights/mardi_final_v9_x86_64.engine
    wts_name: /weights/mardi_final_v9.wts
    model_type: n
    input_h: 512
    input_w: 512
    precision: fp16
    cuda_post_process: g
    conf_thresh: 0.35
    nms_thresh: 0.5
    conf_score_value: 0.3
    is_track: false
    save_dir: /saved_frames
    api_port: 8090
    max_output_bbox: 100
    mjpeg_port: 8080
    camera_index: -1
    camera_width: 1280
    camera_height: 720
